### ISSUE TITLE
Create dedicated "Vouchers" Section in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#10]
Create a new section in the Admin Portal.
[Update 14 Apr]: Put it right after "Campaigns" and call it "Voucher Manager"

Section should be a copy of the Spend Rules section, with the following changes:
- Navigation Menu Title renamed to "Vouchers"
- Page title renamed to "Vouchers"
- Page sub title reworded to "List of Vouchers in OpenMAVN program"
- Hide "Conversion Rate" Column
- Hide "Order" Column
- Hide "Vertical" Column
- Add "Partner" Column
- Rename "Add Spend Rule" button to "Add Vouchers"

**Comment by vitaliidasaev** [comment]
Section with mocked data in the list added, waiting for backend to continue further development.
