### ISSUE TITLE
Email notifications for SME onboarding process

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#109]
As an SME owner
I want to receive email notifications about changes in my registration
In order to know when I have been verified to the system and can create voucher campaigns, or need to provide additional information.

Acceptance Criteria:
**1. Receive email upon registration**
**Given** I am an SME owner
**When** I register to the admin portal
**Then** I should receive an email welcoming me to the system and letting me know what to do next (e.g. create business entity and pass KYC).

"Dear [User],

Thank you for signing up for the OpenMAVN platform!

You're almost ready to start creating digital vouchers for your business.

Start by creating your business profile via the following link. Once your business has been created and verified, you'll be ready to go!

[CREATE YOUR BUSINESS PROFILE]"

**Comment by starkmsu** [comment]
@MarlonMaercz , right now we don't have a separate role for KYC officer, so let's have a special permission level for this. By having it we can search for all users who have such permissions and send them email - bullet point number 2 in story description.
For the point number 3 - it's better to send it to email of admin user who created a partner. Cause we don't have a specific email for a partner, only some email for location that can be for a person who don't need to know about KYC status change

**Comment by MarlonMaercz** [comment]
> @MarlonMaercz , right now we don't have a separate role for KYC officer, so let's have a special permission level for this. By having it we can search for all users who have such permissions and send them email - bullet point number 2 in story description.
> For the point number 3 - it's better to send it to email of admin user who created a partner. Cause we don't have a specific email for a partner, only some email for location that can be for a person who don't need to know about KYC status change

@starkmsu 
1. Regarding KYC Officer Role, we will include it in a future story once we have full clarity on who will conduct KYC (e.g. external provider). For now we will use super admin as a placeholder, but we should be able to easily change who receives the emails should we introduce new user roles.

2. Agreed, email should be sent to the user who created the business. It is assumed that in the majority of cases, the user who creates the business is the business owner or a representative of that business.

**Comment by ElenaBelyavskaya** [comment]
For point 2, since now we base access on permissions, let's link this requirement to admin users with permissions for the Businesses section (in case a user is not superadmin, but has access to Businesses, this user should be able to do KYC too). I will mark this in the desc.

**Comment by starkmsu** [comment]
@MarlonMaercz , we need email designs (at least text message), so Frontend team can create email templates.

**Comment by MarlonMaercz** [comment]
@starkmsu I'll detail the email text and link in description. You can already create repo issues since the content of text is not a blocker.

**Comment by starkmsu** [comment]
@MarlonMaercz , @ElenaBelyavskaya , do we send this email in parallel with email verification email or after SME email was verified?

**Comment by ElenaBelyavskaya** [comment]
@starkmsu we send
1- email upon registration
2 - email upon email verification
This should be the 2nd email (confirming the fact of email verification, not in addition to email after verification).
CC @MarlonMaercz

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev 
There are some deviations from the desc:
1) We need a real name instead of just "User". But since we don't have a person name on this stage, we can go with just "Hello," as a first line
2) Phrase is missing: "You're almost ready to start creating digital vouchers for your business"
3) Can it be [CREATE YOUR BUSINESS PROFILE] button, not just the link?
![image](https://user-images.githubusercontent.com/62890062/84678834-c795dd80-af30-11ea-84ae-13189de9d000.png)

And the link doesn't work in my case:
![image](https://user-images.githubusercontent.com/62890062/84679456-9bc72780-af31-11ea-9ef2-ff19f3988f4f.png)

**Comment by ElenaBelyavskaya** [comment]
@starkmsu cannot register today - getting some new "Technical problem":
![image](https://user-images.githubusercontent.com/62890062/85373704-f107c800-b533-11ea-93da-4bcf8b73b1d9.png)

**Comment by ElenaBelyavskaya** [comment]
The email came, but it's not adjusted...

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , @MarlonMaercz , please retest found issues - fixes were deployed to the internal env.

**Comment by ElenaBelyavskaya** [comment]
@starkmsu can this be tested on https://demo.mavn.ch/ or by some other url?
