### ISSUE TITLE
Ability for Partners to create Vouchers Campaign

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#11]
In the Vouchers section of the Admin Portal #10 , a user should be able to create a new campaign for their vouchers.

- Rename Title from "New Spend Rule" to "New Voucher Campaign"
- Reword sub title from "Enter spend rule details" to "Enter Voucher Campaign details"
- Hide "Order in list on mobile app" field
- Hide "Business Vertical" field
- Hide "Type" field
- Hide Upload Vouchers section
- Add field for "# of Vouchers"
- "Partner" drop-down field should only allow single selection; disable multi-partner selection

**Comment by ataranishin** [comment]
Assign to me

**Comment by vitaliidasaev** [comment]
@kslonik21 after this task will be deployed https://github.com/OpenMAVN/PM/issues/16.
You can start to combine with backend - the new api methods can be found here https://admin-api.mavn.ch/swagger/ui/index.html

**Comment by vitaliidasaev** [comment]
@kslonik21 Admin API deployed, there are new api methods 
`SmartVouchers`, `VoucherCampaigns` here https://admin-api.mavn.ch/swagger/ui/index.html
