### ISSUE TITLE
Hints for Payment Integrations fields

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#113]
As an SME filling details for my company,
I want to be sure I clearly understand meaning of the payment integration fields

**AC's**
GIVEN I am logged in with SME credentials
WHEN I open the New Business form 
THEN there are hints/tooltips* in the Payment Integrations section fields: 
Instance Name: "If the url for accessing Payrexx is example.payrexx.com, then instance name would be "example""
Api Key: "..."

* Should be aligned with UI design of fields on other admin pages

**Comment by vitaliidasaev** [comment]
![image](https://user-images.githubusercontent.com/11960985/82541860-c2c05280-9b59-11ea-8442-55804a7d6cb1.png)

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya added this hint for ApiKey:
In Payrexx Administration website go to menu item "API & Integrations" and copy "Default API Key"

**Comment by Mamyako** [comment]
Tested on Windows/ Chrome 81
