### ISSUE TITLE
Update and clarify fields in Transactions section of Admin Portal

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#115]
As admin user of the platform,
I want to see only useful fields in the Transactions report, in a comfortable order

**AC's**
1. Showing fields in the Transaction grid for "super-admin"
GIVEN I am logged in as admin
WHEN I open Transactions section
THEN I don't see the following fields:
- Location
- Location External ID
- Location Integration Code
- Category
- Status

AND the order and the titles of the columns are as follows (please mind the titles):
- Transaction ID
- Transaction Type _!!! "Smart Voucher" -> Voucher Bought, Voucher Redeemed, Voucher Transferred
- Sender Name
- Sender Email
- Receiver Name _(Partner name in case of Voucher Bought type, Empty in case of Voucher Redeemed, destination in case of Voucher Transferred)_
- Receiver Email  _(Partner email in case of Voucher Bought type, Empty in case of Voucher Redeemed, destination's email in case of Voucher Transferred)_
- Vertical _!!! Rename current "Business Unit"
- Amount _!!! currency should be mentioned together with the value, not in the column title - put to Amount column the currency from backend response_
- Timestamp  _!!! Make the date format user friendly_

2. Showing fields in the Transaction grid for SME admin
GIVEN I am logged in as SME admin
WHEN I open Transactions section
THEN I see the following fields (with the below titles and order):
- Transaction ID
- Transaction Type _!!! "Smart Voucher" -> Voucher Bought, Voucher Redeemed, Voucher Transferred
- Sender Name
- Sender Email
- Receiver Name  _(Partner name in case of Voucher Bought type, Empty in case of Voucher Redeemed, destination in case of Voucher Transferred)_
- Receiver Email  _(Partner email in case of Voucher Bought type, Empty in case of Voucher Redeemed, destination's email in case of Voucher Transferred)_
- Vertical _!!! rename current "Business Unit"_
- Amount _!!! currency should be mentioned together with the value, not in the column title - put to Amount column the currency from backend response_
- Timestamp  _!!! Make the date format user friendly_

**Comment by vitaliidasaev** [comment]
Regarding Category column:
we have Transaction Type and Transaction Category:
![image](https://user-images.githubusercontent.com/11960985/82540144-42005700-9b57-11ea-8b56-490521df227d.png)
Need to decide to show them or choose one of them?

**Comment by vitaliidasaev** [comment]
Regarding columns Location and Status:
They are always empty now:
![image](https://user-images.githubusercontent.com/11960985/82540495-d4085f80-9b57-11ea-8453-20ebdf594372.png)
Need to decide to hide them or implement them on backend and what should be there.

**Comment by vitaliidasaev** [comment]
Regarding column Company (Business ???):
We don't have this field now, need to be implemented on backend first. (FYI: @starkmsu )
If will be implemented then better to name them as "Business Unit "for SME and "Program Member" for SuperAdmin following the same naming through backoffice.

**Comment by vitaliidasaev** [comment]
Regarding Amount (currency should be mentioned together with the value, not in the column title):
@starkmsu need to add Currency to ReportingService after this this task https://github.com/OpenMAVN/PM/issues/106 implementation

**Comment by starkmsu** [comment]
@vitaliidasaev , Currency is already present in response model from Reporting service, so we need to expose the currency in AdminAPI response model. this would be done in OpenMAVN/MAVN.Service.AdminAPI#46

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev corrected the title to "Vertical" - we now show not company, but vertical;
"Location" - we need to show the value (if possible), if not - need to substitute this field to "Company", 
@starkmsu probably I should raise a separate ticket for "Location"; is it a bug or not?

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , Location is empty for now cause there is no event that can be linked to any partner location. Only Redeem operations can have this kind of data.

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , from the last talk with @MarlonMaercz , it seems that we won't have Location info even for smart voucher redeem operations.
So we might consider hiding this column for now.

**Comment by ElenaBelyavskaya** [comment]
@starkmsu we can hide Locations if we have some other data about the partner in transaction. We need to identify transactions by SME somehow. 
There are Receiver Name/Email fields - can they be filled with the SME data? (right now they might be empty e.g. for voucher purchase transactions)

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , let's hide Location and add PartnerName field

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya so the discussed result is:
* put to Amount column the currency from backend response
* hide Location column
* add Partner Name column
* reorder columns following story desc

Please update story description.

**Comment by ElenaBelyavskaya** [comment]
Receiver Name/Email - is it Partner in case of vouchers? @starkmsu

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , @vitaliidasaev , smart voucher campaign update is forbidden when the campaign is published and its start date already happened (Implemented in OpenMAVN/MAVN.Service.SmartVouchers#33). If we want to change this behavior then let's create a separate story and describe allowed changes there.

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev I hope we can show Partner name in Receiver Name field, so I haven't added the new column yet, let's confirm on grooming.
Order is mentioned in the desc, we agreed to make it under this story as far as I remember.
Updated the desc for the other points and added comments about values.

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , @MarlonMaercz , about the logic on how we fill 'Receiver Email' property:
we don't have a link to any partner location in all smart voucher operations, so we can't resolve a location. We can guess only in case this partner has only 1 configured location, and even n this case contact person email might be missing there (since we made it optional by another story).
Using admin email that was used for SME registration might be a solution but if this admin user has multiple configured partners then it also becomes confusing.
What are your thought in this topic?

**Comment by ElenaBelyavskaya** [comment]
In case with receiver, it's important to identify the exact business. Are there any issues with Receiver Name being SME's name (Name of the business)? If not, we can go with Business Name + Business Email, and business email might be empty in some cases.
Until we have a link to locations, let's use email from the only location, and if email is not defined - it's also empty in the Transactions (later on we can move to using First location's email).

**Comment by MarlonMaercz** [comment]
@starkmsu For Voucher Redemption, the SME name can be used in Receiver Name, but Receiver Email can be blank, since you rightly pointed out there is no link to a dedicated email. 
CC @ElenaBelyavskaya

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev @starkmsu where does the "Additional Information" value come from?

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , INfo generation logic is hardcoded in Reporting component, so we can change it if required.

**Comment by ElenaBelyavskaya** [comment]
@starkmsu ok but I mean what is put in the "Additional Info" column now, and which way? :)

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , for now it's being filled only for smart voucher sold events with a voucher short code, all other events have empty info field.
