### ISSUE TITLE
Link business account to customer account in mobile app

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#117]
As an SME registered on the platform 
I want to be able to link my business account to the mobile app
in order to be able to redeem vouchers issued by me from customers

Key Notes:
Add a "Linking code" to an SME entity. This code allows mobile app users to set up the ability to invalidate vouchers via the mobile app without needing credentials for the SME in the admin portal.
Linking code should be 8 digits, alphanumeric (a-z; 0-9) and case insensitive.
Linking code should be related to SME ID
SME ID should be regenerated to ~8 characters from Partner ID. 
QR code can be generated from SME ID and Link code for easy scan and link.

**AC's**

**1. Linking accounts via mobile app**
**GIVEN** I am logged in on mobile app 
 And I have opened Settings
**WHEN** I click on the "Link business account" option
**THEN** I can input an SME Name (or ID) and a "Link Code"
 And then click "Link accounts button"
And the account is then linked to the SME
And I can invalidate vouchers for that SME
 
**2. Linking accounts failed**
**GIVEN** I am logged in on mobile app 
 And I have input incorrect SME Name/ID and Link Code as business credentials
**WHEN** I click "Link accounts button"
**THEN** I get error message "Please check credentials and try again"

**3. Linking business account from multiple mobile accounts**
**GIVEN** I am logged in on mobile app 
 And a business account is already linked to another mobile account/s
 And I have opened Settings
**WHEN** I click on the "Link business account" option
**THEN** I can input SME Name (or ID) and a "Link Code"
And I can link the business account to my mobile account

**Comment by starkmsu** [comment]
@MarlonMaercz , we have no story to get SME Link code from AdminPortal.
The fast solution here would be to enter SME credentials from admin portal when linking to mobile account.
If we don't want to use SME credentials then we need to implement the story to get SME link code first.

**Comment by MarlonMaercz** [comment]
> @MarlonMaercz , we have no story to get SME Link code from AdminPortal.
> The fast solution here would be to enter SME credentials from admin portal when linking to mobile account.
> If we don't want to use SME credentials then we need to implement the story to get SME link code first.

@starkmsu story for linking created #132 . 
We should not use the SME credentials as it poses a security risk. Better to add the link code from the beginning

**Comment by pddimitrova** [comment]
@starkmsu What would the input validation be for the fields (Link code and ID)?

**Comment by pddimitrova** [comment]
@MarlonMaercz @ElenaBelyavskaya  Does it make sense to check whether the user has already linked their account and remove the options from settings if they have? Because they can link only one account to their customer account, correct?

**Comment by MarlonMaercz** [comment]
> @MarlonMaercz @ElenaBelyavskaya Does it make sense to check whether the user has already linked their account and remove the options from settings if they have? Because they can link only one account to their customer account, correct?

@pddimitrova Please check AC#3. A customer should be able to link multiple businesses.

**Comment by ElenaBelyavskaya** [comment]
@MarlonMaercz I have successfully tested N1 and made a basis to test N3.
Could you please test N2 (I cannot do it because I already have linked an account) and finalize testing N3 (it should be tested from 2 accounts and I am blocked because could not reset password on my second account)?

**Comment by ElenaBelyavskaya** [comment]
OK the issue with resetting a password was fixed and I could successfully complete the testing (Android)
