### ISSUE TITLE
[Mobile] Voucher campaign details: Voucher Campaign Details section info is used for mobile app instead of Content For Mobile App section info

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#118]
**Environment:** iOS software version 13.4.1/ Android software version 10

**Precondition**: All fields for used Voucher have been filled in by its owner

**Steps:**

1. Log in to mobile application as a customer using credentials
2. Tap offers tab at the bottom menu of the application
3. Tap to voucher from the precondition of this ticket
4. Compare fields from Content For Mobile App section in Admin part (Voucher manager -> Click Edit button) with actual Mobile content

**Actual result:** Voucher Campaign Details section info is used for mobile app instead of Content For Mobile App section info
**Expected result:**  Content For Mobile App section info is used for mobile app

![1.jpg](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/0e321b06-2574-4bab-b60e-ebb14d4b31e9)
![2.jpg](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/bd963357-b81a-400c-bc1a-e7f014b09994)

**Comment by starkmsu** [comment]
This is BE bug

**Comment by Mamyako** [comment]
Tested on iOS 13.4.1, Android 10
