### ISSUE TITLE
Create individual Vouchers

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#12]
When a voucher campaign is created, usable vouchers should be created and associated with that campaign, based on the number and amount per voucher. 

The voucher should contain the following parameters:
- UID
- Code - generated by UID
- InvalidationCodeHash
- Campaign ID
- Status
- Customer/Owner ID
- Redemption Date
- Purchase Date

For now, they should be stored separately in the Database
InvalidationCode should be mapped to UID

Generated on mobile app
    QR Code

**Comment by starkmsu** [comment]
@MarlonMaercz , current implementation of SmartVouchers service creates a new individual voucher only when it is bought by a customer. No pre-generated individual vouchers are required. So I suggest to close this task, unless there is some good reason to pre-create individual vouchers.

**Comment by MarlonMaercz** [comment]
@starkmsu The details listed above are still relevant for voucher creation though, regardless if they are created in advance or upon purchase. 

When you created SmartVouchers service, did you take the details mentioned above (voucher parameters, storage) into account? If so please link the story and we can close the task if all required actions have been taken in another issue.

**Comment by starkmsu** [comment]
@MarlonMaercz , all thee fields are present in individual voucher properties, MAVN.Service.SmartVouchers was implemented under OpenMAVN/PM#15

**Comment by MarlonMaercz** [comment]
Issue was completed as part of another ticket #15 . Closed as the issue is no longer required.
