### ISSUE TITLE
[Mobile] User isn't redirected to Vouchers menu after buying a voucher

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#128]
**Environment:** iOS software version 13.4.1/ Android software version 10

**Precondition:** All fields for used Voucher have been filled in by its owner

**Steps:**

1. Log in to mobile application as a customer using credentials
2. Tap offers tab at the bottom menu of the application
3. Tap to any voucher to purchase it
4. Click Purchase voucher button
5. Pay for a voucher using your payment credentials
6. Tap Back to Mobile App button after payment has been done
7. Pay attention to the place user redirected to

**Actual result:** User stays on a page with the description of voucher that was bought
**Expected result:** User redirected to Vouchers menu

**Comment by pddimitrova** [comment]
@Mamyako Did this happen both on Android and iOS?

**Comment by Mamyako** [comment]
@pddimitrova On iOS it's sends to Fail page after Success page and Return to Mobile App button just reloads the page

**Comment by pddimitrova** [comment]
> @pddimitrova On iOS it's sends to Fail page after Success page and Return to Mobile App button just reloads the page

@Mamyako What is Fail Page? We don't have Fail Page in the mobile app?

What about Android, what is the issue there? Is it reproducible with all vouchers you have bought, or just particular ones?

**Comment by Mamyako** [comment]
@pddimitrova I meant Fail page at customer website. Let me know I should create another ticket for that.
For android I tried to buy some vouchers and behavior was the same: User isn't redirected to Vouchers menu after buying a voucher

**Comment by Mamyako** [comment]
Tested on iOS 13.4.1/ Android 10
