### ISSUE TITLE
Changes to Program Partners Details in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#13]
In the Partner Locations section on the Partner Details page: 
- Hide "External ID" field
- Hide "Accounting Integration Code" field

**Comment by dmkuchynski** [comment]
i want to pick up this task

**Comment by dmkuchynski** [comment]
@MarlonMaercz do we need to remove or just hide these fields?

**Comment by MarlonMaercz** [comment]
@dmkuchynski Please just hide for now. We may remove in the future or convert those fields to relevant ones.

**Comment by dmkuchynski** [comment]
@MarlonMaercz also need to allow add/edit without these fields on backend side

**Comment by MarlonMaercz** [comment]
@dmkuchynski is it because they are mandatory fields? For any backend required work @starkmsu can help out.

**Comment by vitaliidasaev** [comment]
commented PR, for now better to preserve sending required fields to avoid changes on backend
