### ISSUE TITLE
Generate SME Link code in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#132]
As an SME, 
I want to be able to generate a code for my SME
In order to link mobile app users to invalidate voucher QR codes for my business.

Key Notes:
Add a "Linking code" to an SME entity. This code allows mobile app users to set up the ability to invalidate vouchers via the mobile app without needing credentials for the SME in the admin portal.
Linking code should be 8 digits, alphanumeric (a-z; 0-9) and case insensitive.
Linking code should be related to SME ID
SME ID should be regenerated to ~8 characters from Partner ID.
QR code can be generated from SME ID and Link code for easy scan and link.

AC's:
**1. Generate Link Code**
**Given** I am an SME user
And I have registered for the admin portal
**When** I create a business entity
**Then** a link code should be generated by the system
And I should be able to view it on the business entity page

**Comment by Mamyako** [comment]
@starkmsu @vitaliidasaev 1.There're a couple of console errors related to QR code appear after opening existing business entity or trying to create a new one.

![image](https://user-images.githubusercontent.com/65350611/83384714-86f67a00-a3f0-11ea-80a4-e902001f8835.png)

2. New Business Unit page looks kind of empty from the right side

![image](https://user-images.githubusercontent.com/65350611/83385049-29166200-a3f1-11ea-8613-e0de1f6c3a56.png)

**Comment by vitaliidasaev** [comment]
@Mamyako 1 and 2 fixes deployed.
Representation for partner creation changed.
