### ISSUE TITLE
Consistent naming for Businesses in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#137]
As partner/admin user of the platform 
I want to avoid doubts if synonyms represent the same or different things.

**AC's**
1. Rename the following in the admin UI:
1.1. _For Super-admins_
Program Members -> Businesses
List of Program Members in OpenMAVN program -> List of Businesses in OpenMAVN program 
Add Program Member -> Add Business
New Program Member -> New Business
Edit Program Member -> Edit Business
Enter Program Member details -> Enter business details (in New and Edit)
Program Member Name -> Business Name
Business Unit Code -> Business Code

1.2. _For SMEs_
My Business Entities -> My Businesses
Business Units -> Businesses
List of Business Units in OpenMAVN program -> List of My Businesses in OpenMAVN program 
Add Business Unit -> Add Business
New Business Unit -> New Business
Edit Business Unit -> Edit Business
Enter Business Unit details -> Enter business details (in New and Edit)
Business Unit Name -> Business Name
Business Unit Code -> Business Code

1.3 Update wording for German localization

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya @MarlonMaercz please clarify from perspectives of SuperAdmin and SME Admin.
For example My Businesses for SuperAdmin is too ambitious ;)

**Comment by MarlonMaercz** [comment]
@vitaliidasaev Thanks for the comment. I'll consider when I do the full analysis of this story for next Grooming session

**Comment by vitaliidasaev** [comment]
To follow using the same logic in Voucher Campaign: rename to `Business` there too.
