### ISSUE TITLE
[Admin - Desktop] Voucher manager: Status doesn't change to Completed after End Date reached

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#145]
**Environment:** Windows 10/ Chrome 83

**Precondition:** There's an expired voucher for user in a system 

**Steps:**

1. Log in to Admin Demo site
2. Click on Voucher Manager tab
3. Pay attention to the status of voucher with End Date reached

**Actual result:** Status is Published
**Expected result:** Status is Completed
![image.png](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/c5befe5b-e491-4d33-bf2f-0e890d873bf8)

**AC**
GIVEN a voucher campaign is published
WHEN End_Date is passed
THEN the status of the voucher campaign changes to Completed

**Comment by ElenaBelyavskaya** [comment]
In the case below status didn't change to Completed - it became Unknown:
![image](https://user-images.githubusercontent.com/62890062/84866150-9ecd2f80-b079-11ea-8610-3de9088bad3d.png)

Please review

**Comment by starkmsu** [comment]
@vitaliidasaev , please check statuses mapping on FE, 'Completed' status is returned from AdminApi in this case
