### ISSUE TITLE
[Admin - Desktop] Currency value is RUR instead of RUB

### ISSUE THREAD

**Issue by Mamyako** [OpenMAVN/PM#166]
**Environment:** Windows 10/ Chrome 83

**Note:**  RUR currency doesn't supported by Payrexx

**Steps:**

1. Log in to Admin Demo site 
2. Click on Voucher Manager tab
3. Click Add New Voucher button
4. Fill in Business Unit field
5. Click on Currency dropdown

**Actual result:** There are CHF, EUR, GBP, USD, RUR currencies
**Expected result:** There are CHF, EUR, GBP, USD, RUB currencies
![image.png](https://images.zenhubusercontent.com/5ebd4a65073213c8e8f366ea/49afc1fc-49a9-4bef-939b-707edfbf6140)

**Comment by ElenaBelyavskaya** [comment]
Fixed
