### ISSUE TITLE
As a customer I want to buy a smart voucher from mobile app

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#17]
As a customer I want to buy a smart voucher from mobile app.

1. Vouсher campaign details page must have 'Buy voucher' button*, that will trigger the voucher buying process with a call to CustomerAPI. 
2. CustomerAPI must return a URL to the payment page.
3. Mobile app must open the browser app on the user device with this URL, so the payment process can be done in a safe environment.
4. Customer reserves a voucher while they are in the process of purchasing it. A customer can only reserve 1 voucher at a time, until they have successfully purchased a voucher or cancelled it (#54). 
5. If a customer does not successfully purchase or cancel a reserved voucher, voucher reservation will be lifted after a set (configurable) period of time.
6. After payment is completed (or failed) the payment page will be redirected to customer web site that will contain deep routing link: 
a) In case of successful payment, the web site page should show: 
- The message: "Congratulations, your payment was successful!"
- Possibility to redirect to the list of voucher campaigns and/or to the bought vouchers (where the customer would see the newly bought one). 
The buttons on the customer web site can be called "Back to the list of voucher offers" and "My vouchers".

b) In case when payment failed, the web site page should show: 
- The message: "Something went wrong - your payment failed :( Please try again later.
If the issue continues, please contact the issuer of the voucher."
- Deep routing link must lead back to the voucher campaign details page in mobile app (button name "Back to the voucher details").

---
* We can use current "Redeem" button for that (rename it)

Full detailed flow is described in OpenMAVN/PM#29

Subtasks:
1. openmavn/mavn.service.smartvouchers#5
2. openmavn/mavn.service.smartvouchers#6
3. openmavn/mavn.service.paymentmanagement#1
4. openmavn/mavn.service.paymentmanagement#2
5. openmavn/mavn.service.customerapi#2
6. openmavn/mavn.service.partnerapi#1
7. openmavn/mavn.frontend.customerwebsite#6
8. OpenMAVN/MAVN.Service.OperationsHistory#8
9. OpenMAVN/MAVN.Service.OperationsHistory#10
10. OpenMAVN/MAVN.Mobile#12 
11. OpenMAVN/MAVN.Mobile#18 
12. OpenMAVN/MAVN.Service.PaymentManagement#4

**Comment by starkmsu** [comment]
@MarlonMaercz , @ElenaBelyavskaya , @pddimitrova , please review the story description

**Comment by Mamyako** [comment]
@vitaliidasaev @pddimitrova @starkmsu  please, take a look at this
After testing I can leave some notes to be reviewed:
1.	I can’t see that ‘Redeem offer’ button has been renamed to ‘Buy voucher’
2.	In case of successful payment, the web site page should show The message: "Congratulations, your payment was successful!". For now it’s “Your payment was successful.”
3.	The buttons on the customer website can be called called "Back to the list of voucher offers" and "My vouchers". For now there’s only one button that called “Return to Mobile App”
4.	There’s no possibility to redirect to the bought vouchers, user redirects to the Dashboard in a Wallet
5.	In case when payment failed, the web site page should show: The message: "Something went wrong - your payment failed :( Please try again later.
If the issue continues, please contact the issuer of the voucher.". For now it’s “Something went wrong, please try again or contact support.”
6.	Button from the failed transaction should be named "Back to the voucher details", for now it’s named “Return to Mobile App”
7. Also circles for messages on customer site are having different diameters
Everything else is look pretty well done
![6](https://user-images.githubusercontent.com/65350611/82435404-eec9ce00-9a9c-11ea-8c56-2ad54e2667ca.jpg)
![7](https://user-images.githubusercontent.com/65350611/82435407-effafb00-9a9c-11ea-8eb2-e7494fd266ba.jpg)

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova, @vitaliidasaev please let us know which of the comments from @Mamyako ^ can be fixed today.
For the other ones, we will raise a story for enhancements.

Notification texts are lower priority than the other points.

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya @Mamyako We didn't have voucher list when this was completed. I will create a task for redirection to voucher list instead of dashboard with high priority, but it will not be fixed today.

**Comment by ElenaBelyavskaya** [comment]
@ElenaBelyavskaya @Mamyako to raise ticket/s for leftovers

**Comment by Mamyako** [comment]
Tested using Windows 10 (Chrome 81), Android 10, iOS 13.4.1
