### ISSUE TITLE
Changes to Account page on Mobile App

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#174]
1. Replace Community with My Account on navigation bar
2. Remove My Account icon from explore page
3. Change ordering of items on My Account page

Acceptance Criteria:
1. My Account as a main navigation item
Given I am signed in to the mobile app
When I check on the navigation icons
Then I see the following icons in order:
Explore; Offers; QR Code Scanner; Wallet; (My) Account

(2. Hide Account Icon from Home page)
Given I am on the Explore page of the mobile app
When I look at the top right of the screen
Then I do not see the My Account icon.

2. My Account ordering
Given I am signed in to the mobile app
When I Navigate to the My Account section
Then I see the following tabs in order:
Personal Details; Change Password;  Referral Tracking; Link Business Account; Terms of Use; Privacy Policy; Contact Us; Sign in with your fingerprint; Logout

**Comment by pddimitrova** [comment]
@MarlonMaercz Sign in with fingerprint needs to stay at the bottom together with logout, these are different kind of options that should not sit between other options. Do you think that'd be ok?

**Comment by MarlonMaercz** [comment]
@pddimitrova Ok sure that's fine. Description has been updated.
