### ISSUE TITLE
Add onboarding documentation

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#22]

**Comment by lAnubisl** [comment]
Can this be assigned to me? 
Where should I start working? Shared word document?

**Comment by lAnubisl** [comment]
Next steps:

- [x] 1) Take RabbitMQ local setup. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
into separate markdown and 
put it into https://github.com/OpenMAVN/Welcome as a 'rabbitmq-local-setup.md'

- [x] 2) Take Azure Storage Service local setup. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
into separate markdown and 
put it into https://github.com/OpenMAVN/Welcome as a 'azure-storage-local-setup.md'

- [x] 3) Take Redis local setup. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
into separate markdown and 
put it into https://github.com/OpenMAVN/Welcome as a 'redis-local-setup.md'

- [x] 4) Take Microsoft SQL Server local setup. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
into separate markdown and 
put it into https://github.com/OpenMAVN/Welcome as a 'microsoft-sql-local-setup.md'

- [x] 5) Take VPN connection configuration. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
provide contact person email and name. (ask @starkmsu )
provide instructions for MacOS (either try it on your MacOS or ask in chat for help)
provide instructions for linux (either try it on VM or ask in chat for help)
convert to markdown
put into https://github.com/OpenMAVN/Welcome as a 'vpn-connection-configuration.md'

- [x] 6) Take Dependent service URL configuration. 
from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
Add link to 'vpn-connection-configuration.md'
convert to markdown
put into https://github.com/OpenMAVN/Welcome as a 'dependent-service-configuration.md'

- [x] 7) Take HowToRun.md example for .NET Core Project
from from https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit?usp=sharing
convert to markdown
Add links to 'rabbitmq-local-setup.md', 'azure-storage-local-setup.md', 'redis-local-setup.md', 'microsoft-sql-local-setup.md', 'vpn-connection-configuration.md', 'dependent-service-configuration.md'
put it into put into https://github.com/OpenMAVN/Welcome as 'how-to-run-backend.md'

- [x] 8) Put link to 'how-to-run-backend.md' somewhere in each backend repository

- [x] 9) follow these instructions 'https://github.com/OpenMAVN/MAVN.FrontEnd.BackOffice/blob/master/README.md'
find out if it is enough to start developing frontend application

- [x] 10) follow these steps 'https://github.com/OpenMAVN/MAVN.Mobile/blob/master/README.md'
find out if it is enough to start developing mobile application

**Comment by starkmsu** [comment]
@lAnubisl , please mark completed steps in the list above

**Comment by starkmsu** [comment]
@SandraBaidak , what is pending on this task?

**Comment by SandraBaidak** [comment]
@starkmsu It is completed and uploaded by Nikolay Anastasov.

**Comment by vitaliidasaev** [comment]
@SandraBaidak this gdoc (https://docs.google.com/document/d/1UZJawnSA47umqmbNLFvmUqsqhiRB4NEA2b3zZaYrZ70/edit#heading=h.q6pxbi2d7tgj)
 was converted to .md-file (https://github.com/OpenMAVN/Welcome/blob/master/Developer-Documentation.md - which also available via url https://open.mavn.ch/Developer-Documentation)
