### ISSUE TITLE
As a customer I want to filter offers in the mobile app by customer location

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#27]
As a user, I want to be able to see offers in teh mobile app based on my location

**Acceptance Criteria:**
**1. View offers based on location**
**Given** I am a customer
**When** I click on the Offers page on the mobile app
**Then** I am prompted to allow location services.
**When** I accept location services
**Then** I am presented with a list of vouchers available around me sorted by proximity (ascending; i.e. closest offer first).
**When** I deny location services
**Then** I am presented with all published offers in the app.

Subtasks:
1. openmavn/mavn.service.partnermanagement#16
2. openmavn/mavn.service.customerapi#11
3. openmavn/mavn.mobile#19
4. openmavn/mavn.mobile#20
5. OpenMAVN/MAVN.Service.CustomerAPI#16

**Comment by pddimitrova** [comment]
@starkmsu Will there be an endpoint returning all cities within a country that have voucher offers?

**Comment by pddimitrova** [comment]
@MarlonMaercz @ElenaBelyavskaya What do you think is an appropriate default radius for the offers?

**Comment by pddimitrova** [comment]
@starkmsu Will the sorting by proximity be implemented on the BE or mobile app? I guess it should due to the pagination.

**Comment by pddimitrova** [comment]
@MarlonMaercz @ElenaBelyavskaya We will need copy for the following case: 
User has not enabled location (location is turned off for the device)-> We need to prompt them to turn on location and try again

**Comment by starkmsu** [comment]
@pddimitrova , filtering is already implemented on the backend side

**Comment by Mamyako** [comment]
Decided with @ElenaBelyavskaya that radius of shown vouchers should be 20km

**Comment by Mamyako** [comment]
Tested on iOS 13.4.1, Android 10
