### ISSUE TITLE
Admin Portal Translation to German

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#28]
generate up-to-date file messages.generated.xlf (it has XLIFF 1.2 format) by command
ng xi18n --i18n-format=xlf --i18n-locale en-US --out-file messages.generated.xlf --output-path locale
translate messages.generated.xlf into messages.de-de.generated.xlf
create configuration for german in angular.json, dockerfile and nginx

**Comment by vitaliidasaev** [comment]
Need to do:
- to review all places where we don't have and fix them
- generate up-to-date file messages.generated.xlf (it has XLIFF 1.2 format) by command 
ng xi18n --i18n-format=xlf --i18n-locale en-US --out-file messages.generated.xlf --output-path locale
- translate messages.generated.xlf into messages.de-de.generated.xlf
- create configuration for german in angular.json, dockerfile and nginx

**Comment by vitaliidasaev** [comment]
example
[messages.generated.zip](https://github.com/OpenMAVN/PM/files/4438527/messages.generated.zip)

**Comment by MarlonMaercz** [comment]
thanks @vitaliidasaev, 
1. Is there an easy way to extract only the "< source >" to make it easier to translate?
2. Is there a separate file for the tooltips? Those will also need to be translated.

**Comment by viandreas** [comment]
Lets go step by step and at least get the most important parts translated.
Where can I do that?

@vitaliidasaev @MarlonMaercz

**Comment by vitaliidasaev** [comment]
Used trial of https://crowdin.com/ to translate.
