### ISSUE TITLE
Integrate Payrexx as a payment solution

### ISSUE THREAD

**Issue by viandreas** [OpenMAVN/PM#29]
Payrexx is offering a service called "Plattform" it allows us to collect payment on the app and send it directly to the bank account to the recipient, for example, the voucher issuer.

Here the documentation:
https://developers.payrexx.com/

@MarlonMaercz @ElenaBelyavskaya 
We need to understand from Payrex how to get onboarded.

This is a high prior task as we won't be able to launch without payment services.

Subtasks:
1. openmavn/mavn.service.payrexxintegration#1

**Comment by starkmsu** [comment]
Payment flow (happy path):
1. Customer requests for payment from mobile app, it's forwarded to CustomerAPI
2. SmartVouchers component (SV) reserves smart voucher for this customer
3. PaymentManagement component (PM) is called to get payment request info from SV
4. PM maps the call to payment integration plugin component (plugin) that knows Payrexx integration details
5. Plugin sends generated SuccesUrl, CancellationUrl and other required payment info to Payrexx to create an invoice
6. Plugin receives payment page URL from Payrexx and returns it to PM
7. PM returns URL as a part of response to the original request from mobile app to SV, SV returns to CustomerAPI and it is returned to mobile app
8. Mobile app opens the payment page in the browser
9. After the payment is done Payrexx redirects to SuccesUrl (it was passed when to Payrexx during invoice init API call). SuccessUrl/CancellationUrl lead to pages hosted on the customer web site.
10. Success page shows that the payment was successful and has a deep writing link back to mobile app.
11. On customer web site from query params of SuccessUrl we get invoiceId and call PartnerAPI to validate the invoice
12. PartnerAPI calls PM to validate the invoice
13. PM requests for invoice status from the plugin
14. If invoice status is Paid then PM raises PaymentCompleted event
15. SV handles PaymentCompleted event and marks reserved voucher as a bought one
16. Customer from mobile app can see details of bought individual vouchers.

**Comment by starkmsu** [comment]
Payment flow (fail cases):
2.b - SV can't reserve a voucher for required campaign.
Corresponding error code is returned from CustomerAPI to mobile app

5.b - Payrexx is unavailable
Error code is returned back through the pipeline: plugin -> PM -> SV -> CustomerAPI

8.b - for some reason mobile app is unable to open the payment page in the browser
Customer can cancel payment process from mobile app smart vouchers page 

9.b - Payment is cancelled by customer without Payerxx knowing about it - by closing a browser page for example
There is a cleanup job that marks reserved vouchers as available after some timeout and validating a payment status in Payrexx via PM->plugin check

10.b - Payment is cancelled by from the payment page by customer/Payrexx and CancellationURL is called
'Payment is unsuccessful'page is shown from customer web site in mobile app.
Customer web site parses invoceId from URL query params and makes a call to PartnerAPI to validate invoice.
PartnerAPI -> PM -> plugin 
Plugin returns unsuccessful invoice status to PM and PM raises UnsuccessfulPayment event
SV handles UnsuccessfulPayment event and marks reserved voucher as an available one.
10.c For some reason there was no forwarding from the payment page to both SuccessUrl and CancellationUrl
There should be configured webhook in partner Admin panel on Payrexx side that leads to endpoint of PartnerAPI that validates invoice.
Payrexx must call this webhook after operations is canceled/timeouted and after that the flow will start from PartnerAPI - see 10.b

**Comment by starkmsu** [comment]
@MarlonMaercz , @ElenaBelyavskaya, @vitaliidasaev, @PaterSantyago , please review described flows.

**Comment by viandreas** [comment]
Would it help to get technical support from Payrexx?

I have a call with their CEO this week...


 Viktor Andreas
 Executive Director

 Phone: +41 78 845 82 59
 Email: viktor.andreas@lykke.com
 Website: *www.lykke-business.ch/ <https://lykke-business.ch/>*

**Comment by ElenaBelyavskaya** [comment]
@starkmsu can we test points
2.b
5.b
8.b
9.b
10.b?
How (if yes)?

Other points are successfully tested.

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , yes all these cases can be tested

**Comment by ElenaBelyavskaya** [comment]
Sergey Nesterov 
2.b - when last remaining voucher is available for some campaign, then start reservation flow from 2 customer accounts
Sergey Nesterov 
5.b - some developer can temporarily apply incorrect payrexx URL so it won't be available
Sergey Nesterov 
8.b - should be implemented in mobile app (edited) 
Sergey Nesterov 
9.b - don't do the payment and check that фаеук 10 minutes it's unreserved (edited) 
Sergey Nesterov  
10.b - not sure if payment cancellation is possible from payrexx page

**Comment by Mamyako** [comment]
Tested on Windows 10/Chrome 81, iOS 13.4.1, Android 10
8.b will be tested along with #54  ticket
2.b and 5.b will be tested along with #127  ticket
