### ISSUE TITLE
Hide irrelevant sections on Dashboard Page in the Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#3]
For first release, the following sections should be changed on the dashboard page:
 Hide "Wallet's Balance, MVN" and "Total Referrals"
 Hide "Earn, Top 5 Partners" and "Spend, Top 5 Partners" Sections
 Hide "Top 5 Rules by Participation" widget
 Hide "Leads" Section/Graph

IMPORTANT: Sections should be hidden, not removed. Improvements to these sections will be proposed in separate issues.

**Comment by nanastasov** [comment]
I will take this task
