### ISSUE TITLE
[Admin] Hide Conversion Rate in Program Partners and Redeem Campaigns grid

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#34]
These columns should be hidden (conversion rate cannot be defined via UI at the moment, so the columns don't make sense):
![image](https://user-images.githubusercontent.com/62890062/78871916-bcae6080-7a48-11ea-9c7f-d63afe9ab180.png)

![image](https://user-images.githubusercontent.com/62890062/78875980-fd10dd00-7a4e-11ea-83be-c11b8f8c3c5f.png)

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment issue in order i could assign to you

**Comment by nanastasov** [comment]
I will take this task.
