### ISSUE TITLE
[Admin] Rename subtitles of some pages

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#35]
We need to adjust some of subtitles according to the changes in the portal:
1) Dashboard page: "Statistics and analytics"
2) Redeem Campaign page: "List of redeem campaigns in OpenMAVN program"
3) Program Partners page: "List of partners in OpenMAVN program"
4) Blockchain Operations page: "List of blockchain operations in OpenMAVN program"
5) Transactions page: "List of transactions in OpenMAVN program"

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment issue in order i could assign to you

**Comment by nanastasov** [comment]
I will take this task.
