### ISSUE TITLE
[Admin] Rename "tokens" to "Smart Points" in Admin Portal #2

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#36]
Rename in the highlighted places:
- "Smart points" instead of "Tokens"/"Bonus points"
- "SP" instead of "MVN"

![image](https://user-images.githubusercontent.com/62890062/78874463-b7ebab80-7a4c-11ea-98e2-fad0a75cc8f7.png)

![image](https://user-images.githubusercontent.com/62890062/78876927-62b19900-7a50-11ea-965d-dc8d06956933.png)

![image](https://user-images.githubusercontent.com/62890062/78874572-dfdb0f00-7a4c-11ea-8a04-1ba736d3535f.png)

![image](https://user-images.githubusercontent.com/62890062/78874735-1e70c980-7a4d-11ea-9210-b0e80fb8a942.png)
(same for the Edit page)

![image](https://user-images.githubusercontent.com/62890062/78876318-76103480-7a4f-11ea-9a91-fbbc56fe11e5.png)

![image](https://user-images.githubusercontent.com/62890062/78876477-afe13b00-7a4f-11ea-8b0b-ed4ab27c4550.png)

**Comment by dmkuchynski** [comment]
plas assign to me
