### ISSUE TITLE
[Admin] Renaming Rules to Campaigns in the admin portal

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#38]
In the places highlighted below, "rules" ("action rules") should be replaced with "campaigns":

![image](https://user-images.githubusercontent.com/62890062/78887609-76fd9200-7a60-11ea-85ee-429c0165e212.png)

![image](https://user-images.githubusercontent.com/62890062/78886439-7d8b0a00-7a5e-11ea-97b9-e53a4c40894f.png)
(and accordingly for the Edit page)

![image](https://user-images.githubusercontent.com/62890062/78886633-d9559300-7a5e-11ea-8c6a-98cc2021b0d0.png)

"Spend rules" -> "Redeem campaigns":
![image](https://user-images.githubusercontent.com/62890062/78886864-305b6800-7a5f-11ea-9ebc-88ec0cb2f4b2.png)

![image](https://user-images.githubusercontent.com/62890062/78887072-8af4c400-7a5f-11ea-8f5c-56fcde6c0807.png)

![image](https://user-images.githubusercontent.com/62890062/78887310-e8891080-7a5f-11ea-8fb3-1f3dbb36b4a7.png)

![image](https://user-images.githubusercontent.com/62890062/78887927-073bd700-7a61-11ea-8fa7-35df655779ef.png)

![image](https://user-images.githubusercontent.com/62890062/78888583-3141c900-7a62-11ea-9f08-2115172644f3.png)

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment to be assignable

**Comment by nanastasov** [comment]
I will take this task.
