### ISSUE TITLE
Fix untranslated string places

### ISSUE THREAD

**Issue by vitaliidasaev** [OpenMAVN/PM#40]
Review all places where we don't have translations and update.

Use this command to run german version locally - https://github.com/OpenMAVN/MAVN.FrontEnd.BackOffice/blob/master/README.md#i18n

Depends on https://github.com/OpenMAVN/PM/issues/28

**Comment by vitaliidasaev** [comment]
@nickanastasov please comment to assign to you.

**Comment by nanastasov** [comment]
I will take this task.
