### ISSUE TITLE
Prepare admin portal to work with SME partners

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#41]
As a registered Partner of the platform, I want to have access to the admin tool related to my participation in the program.

When a partner logs in, the following sections and features should be available:

DASHBOARD: availability of data only related for this partner 
- Hide Repeat customers section, 
- Show New/Active/Repeat Customers filtered for partner
- Show Transactions figures related to this particular partner
- Provide Vouchers chart (for this particular partner): Purchased, Redeemed
- In the Smart Points section, show values related to this particular partner

VOUCHER MANAGEMENT: only voucher campaigns associated with this partner should be available (whether created by this partner, or by super-admin of the platform)
- Edit access
- When creating/editing a campaign, this partner should be selected in the Partner filter by default (without possibility to change the selection)
(!) If we would have Vertical parameter - it should be automatically selected as a vertical of this particular partner (and disabled)

MY BUSINESS ENTITIES (renamed Program Partners section):
- Only partners created by this partner admin user should be available
- Edit access
- Contact Details part - the fields should be made Non-mandatory
- Credentials fields - should be deleted
- Include Payment System API Key field - Mandatory

TRANSACTIONS: create a new report that shows voucher transactions related to this individual partner
- Transaction types for operations with vouchers should be introduces (Voucher Reserved/Purchased/Redeemed/Expired...)

SETTINGS:
- My Profile sub-section should open Edit Admin User page for this particular partner admin user
- Change Password page: display it after My Profile page and call "Change Password".

ACCOUNT window: My Profile option should also open the Edit Partner page.
- User name (in the top right corner) should display partner's name.

These pages should not be available (should be hidden): Customers, Campaigns, Blockchain, Admin Users

---
PARTNER ACCESS FLOW:
1. Non-registered partner opens login page and click Register
2. Fill in necessary fields and sign in
3. Admin portal opens My Profile (admin user page for this partner, Settings -> My Profile) and the new partner is proposed to fill in other mandatory fields, so that the partner representative should be able to add organizations
4. The partner representative after that can go to My Organizations (current Program Partners section) and add organizations.
5. When an organization is created and certain necessary fields are filled the partner can create voucher campaigns for this organization.
Necessary fields include:
- Payment service KYC results
- ?? MAVN KYC (TBC)
6. The partner go to Voucher Management section and create campaigns with the created organizations involved. The campaigns appear on the mobile app.
7. Customers find the campaign among offers and obtain the vouchers.
8. Later on, customers visit the partner and redeem the vouchers.
9. The partner monitor the number of customers and obtained/redeemed vouchers in the dashboard and Transaction report.
10. AT any time partner can change password in the Settings->Change Password page.

**Comment by ElenaBelyavskaya** [comment]
Related to https://github.com/OpenMAVN/PM/issues/31

**Comment by vitaliidasaev** [comment]
@starkmsu @PaterSantyago please review current flow and create appropriate related issues for backend.

**Comment by vitaliidasaev** [comment]
maybe we can sync on this on Monday

**Comment by ElenaBelyavskaya** [comment]
Modification of campaigns should be available for partners only after all required fields are filled - #43 
Reconsider the Partner credentials flow #44

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , please convert this to a label and close the task

**Comment by Mamyako** [comment]
@ElenaBelyavskaya @starkmsu please, take a look to this comment
There’re my notes to this ticket:
1.	Contact Details part - the fields should be made Non-mandatory, but now they are mandatory
2.	Statuses aren’t shown in Transaction menu
![10](https://user-images.githubusercontent.com/65350611/82443847-d95ba080-9aaa-11ea-8b0c-a857c5c587bb.jpg)
3.	Password can be changed from the current to a new one if new password is the same as current
4.	User name (in the top right corner) should display partner's name. Is it for collapsed Account state or expanded?
![11](https://user-images.githubusercontent.com/65350611/82444340-c1385100-9aab-11ea-9e9e-5a1d7397573e.jpg)
![12](https://user-images.githubusercontent.com/65350611/82444344-c2697e00-9aab-11ea-896e-1e8a1eddb26a.jpg)

5.	For the PARTNER ACCESS FLOW there should be email verification step before the third step
5.1.	My Profile doesn’t opened automatically after first login, so if it’s meant to be like that, it doesn’t work. Dashboards are opened.
6. My Profile changes can be applied only after user's re-login, is it okay?

**Comment by starkmsu** [comment]
@Mamyako , missing tx status would be added in OpenMAVN/MAVN.Service.Reporting#15 under story OpenMAVN/PM#99

**Comment by ElenaBelyavskaya** [comment]
@starkmsu are all the values the same for the Status field? If they are all like "Complete" we can just hide this field, not wasting time for fixing displaying the values
CC @Mamyako

**Comment by Mamyako** [comment]
Points 1, 3, 4 and 6 need to be done. @starkmsu let me and @ElenaBelyavskaya know, is it possible to fix them today?

**Comment by ElenaBelyavskaya** [comment]
1, 5 and 6 should be fixed.

For 3 and 4 we can raise separate stories. @ElenaBelyavskaya @Mamyako

**Comment by vitaliidasaev** [comment]
> 1, 5 and 6 should be fixed.
> 
> For 3 and 4 we can raise separate stories. @ElenaBelyavskaya @Mamyako

@ElenaBelyavskaya @Mamyako lets create separate tickets for these too. Because this story already has huge amount of subtasks.
FYI: @starkmsu points 1 (make Contact Details fields in Location not mandatory) and 5 (saving flag HasFirstLogin) require backend changes.

**Comment by Mamyako** [comment]
Tested on WIndows 10 / Chrome 83

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , please create separate stories for points 1 and 5 from @Mamyako notes

**Comment by Mamyako** [comment]
@starkmsu They already have been created. #158 and #159
