### ISSUE TITLE
Publishing of voucher campaigns should be available for partners only after all required fields are filled

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#43]
Partners should be able to publish campaigns only after they have provided all information necessary to operate in the platform.

**AC's**
1. Requirements to publish voucher campaigns:
- All currently existing mandatory fields for my Organization profile are filled
- Payment integration details (API Key, Instance Name) are filled
- Number of vouchers must be greater than 0
- Price of Voucher can be 0

2. Newly registered partners should see the Voucher Manager  sections and be able to add a new voucher campaign, but should not be able to change the status of the campaign from Draft to Published - until all the requirements are met.
- This toggle should be disabled while the partner hasn't fulfilled all the requirements on providing the information from point 1:
![image](https://user-images.githubusercontent.com/62890062/81780166-5bb9f280-94f6-11ea-87c0-3bccc5c08176.png)

3. Hint should be provided on hover on the disabled toggle: "To proceed with campaigns, complete providing required information in My Profile".

Subtasks:
1) openmavn/mavn.service.partnermanagement#20
2) openmavn/mavn.service.partnermanagement#22
3) openmavn/mavn.service.adminapi#33
4) openmavn/mavn.service.adminapi#36

**Comment by ElenaBelyavskaya** [comment]
@starkmsu what's the complexity with allowing campaigns with vouchers price = 0?
We need to provide this option: some of the companies might like to initiate a promo once and invite their clients to get a custom or a services for free.

**Comment by starkmsu** [comment]
@ElenaBelyavskaya , not large, I will add a subtask to properly process such vouchers as well.

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya point 3. "To proceed with campaigns, complete providing required information in My Profile" - instead "My Profile" perhaps should be "your Business Unit". Please consider.

**Comment by Mamyako** [comment]
Tested on Windows 10/ Chrome 81
