### ISSUE TITLE
As a customer I want to see available voucher campaigns in mobile app

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/PM#52]
As a customer I want to see available voucher campaigns in mobile app.
There should be paginated list of voucher campaigns in mobile app that shows active voucher campaigns.
Each voucher campaign in the list must be clickable.*
On voucher campaign click it must lead to a page with voucher campaign details:*

- Image*
- Title*
- Owner (partner)*
- Number of available vouchers*
- Voucher price*
- Date of campaign end

* Already implemented on mobile UI

Subtasks:
1. openmavn/mavn.service.customerapi#1
2. UPD: #58 
3. Fetch and display available vouchers in Mobile App openmavn/mavn.mobile#4
4. Update Design for Offers page
5. OpenMAVN/MAVN.Service.CustomerAPI#18

**Comment by starkmsu** [comment]
@marlon, @ElenaBelyavskaya , @pddimitrova , please review story description

**Comment by Mamyako** [comment]
@pddimitrova please, take a look at this:
1.	After discussion with Elena Belyavskaya, we found that Number of available vouchers should be shown in voucher campaign details. For now it’s not implemented. 
2.	Owner (partner) name isn’t changes to "Offer unavailable" message if vouchers are over
![8](https://user-images.githubusercontent.com/65350611/82437157-a4961c00-9a9f-11ea-9b8c-50c75b337d3a.jpg)
![9](https://user-images.githubusercontent.com/65350611/82437160-a52eb280-9a9f-11ea-971e-813e73dbbc42.jpg)

**Comment by pddimitrova** [comment]
@starkmsu Aren't only available campaigns loaded?
@Mamyako @ElenaBelyavskaya For voucher count, this is not implemented in the provided design. If it is necessary, we need to discuss it with the designer and apply accordingly.

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova we had the number of remaining vouchers before, I didn't expect it would be removed, but I see your point re the design mockup. Please let us know if you need an edited design mockup to return the number of vouchers to the offer or it can be done without assistance from designer?

@MarlonMaercz any objections? I believe number of vouchers is useful for the user, and also from the marketing point of view.

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova you are right, we decided not to show vouchers out of stock in the offers; I edited the description.
@Mamyako the partner name will just be there, and we show only offers where there are yet some vouchers.

**Comment by starkmsu** [comment]
About this issue: ""Owner (partner) name isn’t changes to "Offer unavailable" message if vouchers are over""
@pddimitrova ,  this is for a case when a customer bought a voucher but haven't redeemed it before voucher campaign expiration. So such voucher should have Expired status and be removed from the list of bought vouchers. So we can only see voucher buy operation in operations history.

**Comment by ElenaBelyavskaya** [comment]
@starkmsu no this story is about Offers, not a list of Bought vouchers...

**Comment by Mamyako** [comment]
Tested using Windows 10 (Chrome 81), Android 10, iOS 13.4.1
