### ISSUE TITLE
As a customer I want to be able to cancel unfinished voucher payment from mobile app

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/PM#54]
As a customer buying a voucher I want to be able to cancel a payment in progress.

1. On the page with bought smart vouchers list we should be able to see pending voucher payments.
- We need to show the Pending status for such vouchers
- We should have them under special tab in the list of vouchers: create two tabs - All and Pending; in the latter one, filter vouchers by the Pending status
2. When clicked on a row of a pending voucher payment, it must lead to a page with voucher details - same page for details for bought smart voucher but with 'Cancel payment' button.
3. 'Cancel payment' button click should initiate the flow of smart voucher buying cancellation from CustomerAPI.
4. After cancellation is finished reserved voucher must be marked as available and can be reused for the next reservation attempt.
And this voucher should disappear from the user's app.
5. If a customer already have a reserved voucher, the customer should not be able to reserve another instance of this voucher.
The message should be given: "Please finalize purchase of already reserved voucher first".
6. If a voucher is reserved for a customer, but the customer has not finished payment, Then a 'Continue Payment' button should appear on the voucher details page. This button links to the payment for the voucher via payment integration provider
7. A customer can only have 1 reserved voucher per voucher offer at any given time. 

Subtasks:
1. openmavn/mavn.service.customerapi#4

**Comment by starkmsu** [comment]
@MarlonMaercz , @ElenaBelyavskaya , @pddimitrova , please review this story

**Comment by pddimitrova** [comment]
@MarlonMaercz has the design team been informed of this need? Currently, the design consists of only the finalised purchases.

**Comment by Mamyako** [comment]
"8.b - for some reason mobile app is unable to open the payment page in the browser
Customer can cancel payment process from mobile app smart vouchers page"
point from ticket #29 will be tested along with this ticket

**Comment by pddimitrova** [comment]
@MarlonMaercz @starkmsu Should we take out the part about continuing the purchase from this story into another one? Everything else has been completed and ready to be moved to Ready for Testing.

**Comment by starkmsu** [comment]
@pddimitrova , you can decide this for yourself, cause backend part is finished here for both cancellation and continuation

**Comment by Mamyako** [comment]
Tested on Windows 10/Chrome 83
iOS 13.4.1, Android 10
"Continuing the purchase" part of ticket will be implemented in ticket #165
