### ISSUE TITLE
Partner should be able to enter one's payment integration details in Admin Portal

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#55]
As a partner, I should be able to enter my payment integration details in AdminPortal.

1. Required payment integration details are specific for particular payment provider.
That's why AdminPortal must fetch a list of available payment providers and list of required fields for each provider.
And as a partner, I should be able to add a payment provider from available list.
2. After payment provider is added in AdminPortal, a list of required integration properties must be displayed. 
Some properties are secrets and values for such properties can't be fetched from the backend, so only some dummy values hidden like a password can be shown for such properties.
- Non-secret properties can be fetched from the backend API and can be shown as plain text.

List of subtasks:
1) openmavn/mavn.service.customerprofile#12
2) openmavn/mavn.service.paymentmanagement#3
3) openmavn/mavn.service.adminapi#15
4) openmavn/mavn.service.adminapi#29
5) openmavn/mavn.frontend.backoffice#62
6) OpenMAVN/MAVN.Service.PaymentManagement#7
7) openmavn/mavn.service.payrexxintegration#2
8) OpenMAVN/MAVN.Service.AdminAPI#35

**Comment by Mamyako** [comment]
This ticket can't be fully tested since only Payrexx is available as payment provider. Required fields are static because no changes in payment provider can be made.

**Comment by ElenaBelyavskaya** [comment]
@Mamyako Vasilisa we go with just Payrexx at this stage, so this is fine.

**Comment by ElenaBelyavskaya** [comment]
Successfully tested on the demo env admin portal.
