### ISSUE TITLE
Enable SMEs to be KYC'ed in Admin Portal

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#56]
As a admin of the Admin Portal who is able to KYC SME's, I want to be able to review and confirm that an SME can create voucher campaigns, in order to ensure that fraudulent actors cannot create scam voucher campaigns.

Key points:
- Add a status for an SME for "KYC Status" with Unverified, In Review, Verified, Rejected.
- Add KYC Status as column in list of Organizations
- Disable SME's from publishing voucher campaigns (they can still create under draft status) until KYC status is "Verified" 
- Assumption for this story that 1 registered SME sets up 1 SME organization
- Process of reviewing an SME for KYC shall remain manual and external to the system for this story. 

Acceptance Criteria
**1. New SME registers for the app**
**Given** I am a SME registering for the OpenMAVN Platform admin portal
**When** I create a new business organization
**Then** the KYC status for that business is set to "unverified" by default
And I can only save Voucher campaigns as drafts
(And my business does not show up in the list of partners when creating a campaign)

**2. Change KYC Status**
**Given** I am an admin super user
And SMEs have been created by business users
**When** I click on the list of SMEs
**Then** I can see a the KYC status column on the list 
And I am able to open the business profile
And I can change the KYC status field of an organization
And the timestamp and user who changed the field are shown on the organization page

**3. Reject KYC of an SME**
**Given** I am able to change the KYC status of an SME
**When** I change the status to "Rejected"
**Then** a comment box is shown
And the comment box is mandatory
And I should fill in the reason for rejection
And the box should be hidden when KYC status is not "Rejected"
And the hidden comment box should not prevent the user from saving the business profile if it is not shown

Subtasks:
1. openmavn/mavn.service.kyc#1
2. openmavn/mavn.service.kyc#2
3. openmavn/mavn.service.partnermanagement#27
4. openmavn/mavn.service.adminapi#39

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya 
AC1. "(And my business does not show up in the list of partners when creating a campaign)". <- Need to remove or change flow of Publishing.
If the list of partners will be empty - then user couldn't create even Draft.
For Publishing we already have protection: it checks the selected Business Unit for allowing to Publish.

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev in case of the KYC statuses except for "Verified" the hint below is not correct - please change the text to "Requires the company KYC to be passed" (in my case, the company has all the details):
![image](https://user-images.githubusercontent.com/62890062/84674731-9cf55600-af2b-11ea-972f-4d17b7cdcb77.png)

**Comment by ElenaBelyavskaya** [comment]
We need to enhance selection of statuses, proposals:

1. Only statuses available for selection should be shown in the drop-down
2. "Requires Data" option:
2.1. Rename to "Request information"
2.2. Show in Histories (for admin and for the SME) as "Information required"
2.3. Comment should be mandatory for this option
3. Statuses in the drop-down should be shown in real order:
- Unverified
- In review
- Request information
- Verified
- Rejected

CC @MarlonMaercz 
@vitaliidasaev can this be done under the same story?

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya changes deployed. Please recheck and confirm.

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev selection/availability of statuses looks great. 
Though each time I open an SME on edit (with any status), the field shows 'New KYC Status', while it should show the currently saved status (same as in the grid):
![image](https://user-images.githubusercontent.com/62890062/85275874-41721d80-b481-11ea-9c9b-872707245871.png)

**Comment by vitaliidasaev** [comment]
@ElenaBelyavskaya this dropdown has only available statuses to which you can change. 
It doesn't make sense to show current status there because it already shown in History and in Basic Info.
![image](https://user-images.githubusercontent.com/11960985/85665584-38bd5980-b6c4-11ea-8567-6f01930ffc6e.png)

**Comment by ElenaBelyavskaya** [comment]
@vitaliidasaev I agree, but in case we have the current status shown behind - without this, user might not see the status (would need to find it), so it's not convenient that the status is in another section.
Let's place "KYC Status" in the KYC Status section - this is the most proper section for this field (first Status, then New Status).

**Comment by vitaliidasaev** [comment]
Ok, thanks. Now it is more clear. Will do.

**Comment by vitaliidasaev** [comment]
Current KYC Status added.
