### ISSUE TITLE
Ability to see Bought Vouchers on the mobile app

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#57]
Vouchers Page - As a customer, I want to see vouchers that I bought in order to view their details and redeem them

1. List of vouchers should look approximately like this:
![image](https://user-images.githubusercontent.com/62890062/80182757-de424700-8607-11ea-86d4-7135dcc1fc86.png)
The list should show:
- Voucher image
- Voucher title
- Voucher price
- Issued partner name

Edit as of 19.05.2020:
This is the latest design of the Bought Vouchers Screen:
<img width="374" alt="Screenshot 2020-05-19 at 13 20 34" src="https://user-images.githubusercontent.com/62870927/82315271-bdd19680-99d3-11ea-8fbc-cc8323aa6bd4.png">
For the MVP we are most probably not doing the carousel pagination rather than a plain list.

**Comment by MarlonMaercz** [comment]
This story only covers the page to view purchased vouchers. Viewing the additional details for the vouchers are covered in #53

**Comment by Mamyako** [comment]
Tested on Android 10, iOS 13.4.1 looks good as a plain list.
