### ISSUE TITLE
Customer should only see a list of vouchers on the Offers screen

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#58]
As a customer, I want to only see a list of vouchers on the offers screen (i.e. remove earn and redeem tabs)

1. Hide the Earn/Redeem tabs
2. Display only vouchers in the list of offers
---
Can be a sub-task for #52

**Comment by starkmsu** [comment]
@pddimitrova , if there shouldn't be any more mobile subtasks then please move this story to 'Ready for Development' category

**Comment by Mamyako** [comment]
On Android (software version 10) mobile application it looks good for me, can see the list of vouchers, can access them through application, Earn/Redeem tabs are hidden. But I can't see any related to this ticket changes on iOS (software version 13.4.1). There're only Earn/Redeem tabs are available. Will changes be applied for iOS? That's how Offers page is shown on iOS now
![image](https://user-images.githubusercontent.com/65350611/82213070-3ecd5700-991c-11ea-87fa-179847e46f83.png)

**Comment by pddimitrova** [comment]
@Mamyako There is no updated iOS app version yet. Will ping you as soon as I have it built.

**Comment by pddimitrova** [comment]
@Mamyako are we in position to close this now?

**Comment by Mamyako** [comment]
Tested on iPhone iOS software version 13.4.1/ Xiaomi A2 Android software version 10
