### ISSUE TITLE
Geolocation for partner organization

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#62]
As a partner admin user I want to be able to input geolocation for my organizations (in Location section)

**AC's**
When editing or creating a new organization, in the Location section of the organization's page:
1. Map should be displayed:
a) Empty for new organization
b) With a mark on it for the existing organization (according to Address field)
1.1. From design point of view, map can be located in the right; all the fields can be re-arranged vertically in the left for the better layout

2. Address field creates a location on the map
2.1. Address filed should show hint: "Input address or mark point on the map"
2.2. Address input in this field should be transformed automatically into a point on the map
2.3. Point on the map should be automatically shown as soon as address is input
2.4. After address is input, the field should still allow editing; once the address is updated the point on the map should be updated to

3. Pointing on the map fills in the address field
3.1. A user can navigate the map to find their business's location
3.2. The business owner can pin a location on the map, which will fill the address field with the address of the pin on the map.
3.3. Putting a pin on the map will override any existing addressed filled in the address field. 

Subtasks:
1. openmavn/mavn.service.adminapi#26
2. openmavn/mavn.frontend.backoffice#60
3. OpenMAVN/MAVN.Service.PartnerManagement#12
4. OpenMAVN/MAVN.Service.SmartVouchers#26
5. OpenMAVN/MAVN.Service.PartnerManagement#23

**Comment by starkmsu** [comment]
@MarlonMaercz , @ElenaBelyavskaya , do we allow to add multiple locations for SME? if we do then how do we select what locations are available for some particular voucher campaign? If there is only 1 location for a partner it can be returned as a location for a voucher campaign but there might be a case that only some subset of existing locations supports this voucher campaign. I suggest to add locations selection for multiple locations case during voucher campaign creation.

**Comment by MarlonMaercz** [comment]
> @MarlonMaercz , @ElenaBelyavskaya , do we allow to add multiple locations for SME? if we do then how do we select what locations are available for some particular voucher campaign? If there is only 1 location for a partner it can be returned as a location for a voucher campaign but there might be a case that only some subset of existing locations supports this voucher campaign. I suggest to add locations selection for multiple locations case during voucher campaign creation.

For the scope of this story, the geolocation will be based on the SME's location(s) section; an SME can have multiple locations, each with a corresponding address and point on a map.
 
A voucher campaign will be for all locations of the business, regardless of how many locations there are (i.e. 1 voucher to 1 business to n locations). The ability to define vouchers based on a number of SME locations may be developed at a later stage.

**Comment by Mamyako** [comment]
As I can see now, if location was set and then changed to non-existing location, point on a map stays at the last founded location, but Location field remains filled in with location that can not be found. After saving and reentering Business Unit, nothing changes: wrong filled location name with a point in a map.
@vitaliidasaev  @nickanastasov please, let @ElenaBelyavskaya  know can it be fixed today or not

**Comment by ElenaBelyavskaya** [comment]
@ElenaBelyavskaya @Mamyako - we need to raise tickets for the incorrect behavior
