### ISSUE TITLE
Select partner locations and vouchers via a map on mobile

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#63]
As a customer, I want to be able to see voucher offers on a map and select them, in order to see the offers around me in a more visual way

**Acceptance Criteria:**
**1. Open localized Map in Mobile app**
**Given** I am a customer
And I am logged into the mobile app
And I am on the offers page
And I have accepted location services #27 
**When** I click on a location button on the top right of the offers page
**Then** a map is opened within the mobile app
And the map is centered on my location with a zoomed radius of 2km

**2. Open generalized Map in Mobile app**
**Given** I am a customer
And I am logged into the mobile app
And I am on the offers page
And I have denied location services #27 
**When** I click on a location button on the top right of the offers page
**Then** a map is opened within the mobile app
And the map is centered on Switzerland
And I can see all offers available via the map.

**3. Select Vouchers from Map**
**Given** I am on the map in the mobile app
And SMEs have entered a valid address in the admin portal
**When** I access the map
**Then** I am able to view SMEs on the map offering vouchers
And I can click on them
And I can see the selection of vouchers that are offered
And I can select to purchase those vouchers

**Comment by MarlonMaercz** [comment]
@pddimitrova If a customer rejects location services, which offers appear on the offers list? How will the app know which offers to show from which cities?

**Comment by pddimitrova** [comment]
@starkmsu @vitaliidasaev We will need to add partner logo for each partner. The pins on the map in the design are the logos

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova I tested and got some comments:
N1: Location is defined, but the radius is too small (not 2 km)
N2: If geo location is off on my mobile, the app requests to turn it on, but after I do so, the map is shown:
- for the whole world (should be Switzerland)
- without offers (the map should show pins for offers)
N3: Failed to select vouchers - nothing happens when I tap the pins

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya Ok, I will fix the issues. However, make sure your app is updated to the latest version since clicking pins was only introduced in it

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova yes, I tested with the latest version. So it's weird pins are not working on my end...

**Comment by ElenaBelyavskaya** [comment]
Tested version 0.1.0+1:
N1,2: with Geo location **On** - no offers displayed (both in the list and on the map);
with Geo location **Off** - 2 offers displayed.

Also not sure why only 2 - there are more published offers in admin, and addresses look defined on the map in the admin)
(Maybe the issue with geo location is similar to that in #124)

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya Please review build 0.1.0+2

**Comment by MarlonMaercz** [comment]
@pddimitrova 
AC1: Pass
**AC2: Fail: I was unable to see all offers when focused on Switzerland. This could be achieved when selecting Switzerland explicitly. However only 2 locations showed up, and I suspect there should be more...**
AC3: Pass
CC @ElenaBelyavskaya

**Comment by pddimitrova** [comment]
@MarlonMaercz In Switzerland there were only 2 locations indeed and they're both shown.
