### ISSUE TITLE
Partner to see vouchers bought by customers in Transactions section on admin portal

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#68]
As a partner, I want to see vouchers bought by customers in transaction section on admin portal

**AC**
Transaction type for vouchers should be created and voucher transactions should be shown in Transactions.

**Comment by MarlonMaercz** [comment]
@ElenaBelyavskaya  We have implemented this already. Please update description, test the feature (move to testing column), and close when completed.

**Comment by Mamyako** [comment]
Tested on Windows 10/ Chrome 81
