### ISSUE TITLE
Customer to see transactions in Transactions section on the wallet page

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#69]
As a customer, 
I want to see my transactions in Transactions section on the wallet page, 
In order to track my voucher purchases and redemptions.

https://projects.invisionapp.com/share/2HWW3L8EGDU#/screens/417162588
Separate tab for transactions:
https://projects.invisionapp.com/share/2HWW3L8EGDU#/screens/417162589
(we can start without additional filters, just a list of transactions)

Acceptance Criteria:
**1. View voucher transactions**
**Given** I am a customer of the mobile app
And I have purchase a voucher
**When** I navigate to the wallet page
**Then** I can see a transaction tab
And I tap on the Transactions tab
And I can see a list of my transaction history (Vouchers purchased, vouchers redeemed, Vouchers shared, Smart Points earned/spent)
And the transaction history is sorted Desc
And direction of the transactions is visually indicated (by color, by +/- signs)

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya Is this related to Bought Vouchers somehow? We already have a list of Bought vouchers on the Wallet page and adding Transaction History on the same screen will overcrowd it.

**Comment by MarlonMaercz** [comment]
Moving back to Analysis as we need to more clearly define how we want this to be set up and designed on the mobile app. 
@ElenaBelyavskaya @MarlonMaercz

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya Since we have both Transactions and Dashboard(which actually shows the transactions), which one are we referring to here?

**Comment by MarlonMaercz** [comment]
> @ElenaBelyavskaya Since we have both Transactions and Dashboard(which actually shows the transactions), which one are we referring to here?

We will use the transaction tab. The design is linked in the description. Note that there is an error in the design which will be changed. Transaction list should be under the transaction tab, not the dashboard tab.

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova transaction list is about all transactions, not just bought vouchers; yes, it's a separate screen (apart from the list of bought vouchers)

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya You have also attached a link for the dashboard. I suggest keeping the dashboard(the one with analytics and chart) separate from Transaction History for now and deprioritize Dashboard for MVP since it's not essential.

**Comment by ElenaBelyavskaya** [comment]
All good, just statuses should be in the past: Received, Sent, Purchased...
