### ISSUE TITLE
Changes to Earn Campaigns Details in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#8]
In Earn Rules Details page:
- Rename Title from "Earn Rules" to "Earn Campaign"
- For subtitle, rename from "Enter earn rule details" to "Enter Earn Campaign details"
- In Actions section, Filter Event field to hide any rules related to "Hospitality" and "Real Estate"
- Hide Staking Amount checkbox and text

**Comment by ataranishin** [comment]
Assign to me please
