### ISSUE TITLE
Sending vouchers to existing customer

### ISSUE THREAD

**Issue by ElenaBelyavskaya** [OpenMAVN/PM#83]
As an owner of voucher I want to be able to send it to another customer of the platform

**AC's**
1. Sending voucher - Happy case
GIVEN I have  a voucher bought
WHEN I open my voucher
THEN I can send it to my friend with the app by _scanning QR code of my friend OR_** inputting the email with which my friend is registered on the platform
 AND the voucher will disappear from my wallet and appear on the friend's app  
 AND corresponding transactions will be recorded (on both ends and in the admin panel)

2. Sending voucher - Unhappy case
WHEN I try to send my voucher and use incorrect QR code or email (not registered in the platform)
THEN I get an error message: "Sending voucher failed. Please verify you are using a correct _QR code/_**email and try again."

** QR code is postponed for future

**Comment by ElenaBelyavskaya** [comment]
Described the case when my friend has the app.
We agreed to have additional story for the case when the friend is not yet registered in the platform, right?

**Comment by pddimitrova** [comment]
@MarlonMaercz @ElenaBelyavskaya For this to work, we need to expose the customer's QR code somewhere. Where would we do that?

**Comment by ElenaBelyavskaya** [comment]
@pddimitrova I assumed we use the QR code button for that - the recipient clicks this button on his mobile and shows the QR code to the sender, the sender scans this QR code.
Will it work?

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya If you are talking about the button on the bottom bar, then no, this button. is for scanning. If we decide to use it for showing the user's own QR code, then we need to find a place where we can scan vouchers from

**Comment by MarlonMaercz** [comment]
@pddimitrova Exposing receiver's QR code is not required for this story. First iteration can be done by the sender defining the email that the voucher should be sent to.

**Comment by ElenaBelyavskaya** [comment]
Ah correct @pddimitrova. 
I agree with @MarlonMaercz that we can start with just sending by email.
(Later on we can introduce client's QR code - we would need a separate screen/button for that)

**Comment by ElenaBelyavskaya** [comment]
Testing with Android.
I have successfully sent a voucher to a friend. Trying to send another voucher (to any email, registered or not) - but the Send Voucher button is not available (it's grey and hanging). I had to go back, close the app and enter PIN again - it helped to enable the button.
@pddimitrova is it some known issue?

**Comment by pddimitrova** [comment]
@ElenaBelyavskaya Yes, and it's been fixed, but I have not released a new build. Let me create a new build with some fixes and I will ping you to check it out :)
