### ISSUE TITLE
Changes to Spend Action Rules Section in Admin Portal

### ISSUE THREAD

**Issue by MarlonMaercz** [OpenMAVN/PM#9]
On the Spend Action Rules section in the Admin Portal:
- Rename "Spend Action Rules" to "Redeem Campaigns" on the Navigation Menu
- Rename Section Title from "Spend Rules" to "Redeem Campaigns"
- Reword "List of Spend Rules in referral program" to "List of Spend Rules in OpenMAVN program"

**Comment by ataranishin** [comment]
Please assign to me
