### ISSUE TITLE
As a partner admin I want to see Transactions report that shows voucher transactions related to me

### ISSUE THREAD

**Issue by vitaliidasaev** [OpenMAVN/PM#99]
TRANSACTIONS: report that shows voucher transactions related to this individual partner

Transaction types for operations with vouchers should be introduces (Voucher Reserved/Purchased/Redeemed/Expired...)

Subtasks:
1. OpenMAVN/MAVN.Service.Reporting#10
2. openmavn/mavn.service.adminapi#27
3. openmavn/mavn.frontend.backoffice#68
4. OpenMAVN/MAVN.Service.Reporting#15

**Comment by starkmsu** [comment]
@vitaliidasaev , are any frontend subtasks needed in this story?

**Comment by Mamyako** [comment]
Can't see changes with Status column. Payment from PayPal to buy Peaching voucher was made, can see changes in Bought vouchers, but there's no changes in Transactions page for 30 minutes after transaction (after that time it appears)
![13](https://user-images.githubusercontent.com/65350611/82466610-5269f080-9ac9-11ea-8397-69afe119e6b8.jpg)
![15](https://user-images.githubusercontent.com/65350611/82466715-6d3c6500-9ac9-11ea-9d86-96326c9af6e1.jpg)
![14](https://user-images.githubusercontent.com/65350611/82466620-5433b400-9ac9-11ea-9699-8ea5b8cef2e6.jpg)
